channels:
- conda-forge
dependencies:
- aimsgb =1.1.0
- ase =3.22.1
- atomistics =0.0.6
- coveralls
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.10.0
- matplotlib-base =3.8.1
- mendeleev =0.14.0
- mp-api =0.37.5
- numpy =1.26.0
- pandas =2.1.2
- phonopy =2.20.0
- pint =0.22
- pyiron_base =0.6.8
- pyscal =2.10.18
- scikit-learn =1.3.2
- scipy =1.11.3
- seekpath =2.1.0
- spglib =2.1.0
- structuretoolkit =0.0.11
